# Generated by Django 5.2.2 on 2025-06-07 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(help_text='Auto-increment primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the paper', max_length=500)),
                ('authors', models.TextField(help_text='Authors of the paper (comma-separated or JSON format)')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, null=True, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Publication year')),
                ('journal', models.CharField(blank=True, help_text='Journal or conference name', max_length=200)),
                ('abstract', models.TextField(blank=True, help_text='Abstract of the paper')),
                ('keywords', models.TextField(blank=True, help_text='Keywords associated with the paper')),
                ('url', models.URLField(blank=True, help_text='URL to the paper (if available online)', validators=[django.core.validators.URLValidator()])),
                ('arxiv_id', models.CharField(blank=True, help_text='arXiv identifier', max_length=50)),
                ('pdf_content', models.BinaryField(blank=True, help_text='PDF file binary content stored in PostgreSQL', null=True)),
                ('pdf_filename', models.CharField(blank=True, help_text='Original PDF filename', max_length=255)),
                ('markdown_content', models.TextField(blank=True, help_text='Markdown content of the paper')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this paper record is active')),
                ('primary_domain', models.CharField(help_text="Primary research domain (e.g., 'deepmd', 'abacus', 'unimol', 'ai4s')", max_length=100)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for organization')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'db_table': 'papers',
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['year'], name='papers_year_054a3e_idx'), models.Index(fields=['doi'], name='papers_doi_78a1f6_idx'), models.Index(fields=['primary_domain'], name='papers_primary_ff8358_idx'), models.Index(fields=['created_at'], name='papers_created_e3b4e0_idx')],
            },
        ),
    ]
