# Generated by Django 5.2.2 on 2025-06-07 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, help_text='Abstract of the paper', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(blank=True, help_text='arXiv identifier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, help_text='Journal or conference name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords associated with the paper', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown content of the paper', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_filename',
            field=models.CharField(blank=True, help_text='Original PDF filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for organization', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the paper (if available online)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
