# Generated by Django 5.2.2 on 2025-06-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0002_alter_paper_abstract_alter_paper_arxiv_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, null=True),
        ),
    ]
