# Generated by Django 5.2.2 on 2025-06-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0003_alter_paper_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='markdown_filename',
            field=models.CharField(blank=True, help_text='Original Markdown filename', max_length=255, null=True),
        ),
    ]
