# Generated by Django 5.2.2 on 2025-06-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0004_paper_markdown_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='markdown_filemd5',
            field=models.CharField(blank=True, help_text='MD5 hash of the Markdown file', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_filemd5',
            field=models.CharField(blank=True, help_text='MD5 hash of the PDF file', max_length=32, null=True),
        ),
    ]
