# Generated by Django 5.2.2 on 2025-06-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0005_paper_markdown_filemd5_paper_pdf_filemd5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='markdown_content',
            field=models.BinaryField(blank=True, help_text='Markdown file binary content stored in PostgreSQL', null=True),
        ),
    ]
