# Generated by Django 5.2.2 on 2025-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0007_rename_pdf_content_paper_origin_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2025, help_text='Publication year', null=True),
        ),
    ]
