# Generated by Django 5.2.2 on 2025-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_db', '0008_alter_paper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='fastgpt_collectionId',
            field=models.CharField(blank=True, help_text='FastGPT collection ID', max_length=100, null=True),
        ),
    ]
